Delete Main.java
deleting Main.java causing problem while want push new commit:
PS C:\Users\el-li\OneDrive\Ausbildung\Codes\Java\WSH-Raetsel\WSH-Switch-Console> git push
To https://github.com/Nima-MM/WSH-Switch-Console.git
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'https://github.com/Nima-MM/WSH-Switch-Console.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.